# -*- coding: utf-8 -*-
"""
Compiler for the Master Bibliography Catalogue of 200+ Khasi Works.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "khasi" / "culture" / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
CATALOGUE_PATH = DATA_DIR / "khasi_bibliography_catalogue.json"

RAW_CATALOGUE = [
    # A. Major Khasi novels and fiction
    {"id": 1, "title": "Ka Pung Ka Jingieit", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 2, "title": "U Shanbor bad u Wadbor", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 3, "title": "Ka Jingiaishah", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 4, "title": "Nga Dang Ieit Ia Phi", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 5, "title": "Ka Jingieit Bajanai Ia Phi", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 6, "title": "Ha Phi Nga Aiti", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 7, "title": "Balei Tang Ia I Thei?", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 8, "title": "Nga Dang Kynmaw", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 9, "title": "Ka Biria Dei Por U Sbe Sing", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 10, "title": "U Bieit Bad Ka Khun U Patsha", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 11, "title": "Nga Khlem Poi Pyrkhat", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 12, "title": "Ngan Ap Ia Phi", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 13, "title": "Tuid Ummat Ksiar – Volume I", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 14, "title": "Ka Nongkylliang", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 15, "title": "Ngam Banse", "author": "Minimon Laloo", "genre": "Original Khasi literature", "type": "Novel", "language": "Khasi", "is_translation": False},
    {"id": 16, "title": "Ka Jingieit Ba Nylla", "author": "F.S. Lyngdoh", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},
    {"id": 17, "title": "Ka Samla Nongkyndong", "author": "H.W. Sten", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},
    {"id": 18, "title": "Ka Jingiaid U Pilgrim", "author": "John Roberts", "genre": "Khasi translations / adaptations", "type": "Fiction / Allegory", "language": "Khasi", "is_translation": True, "original_work": "The Pilgrim's Progress by John Bunyan", "digitized": True},
    {"id": 19, "title": "Kam Kalbut", "author": "W. Tiewsoh", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},
    {"id": 20, "title": "Ki Ummat Jingieit", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Short stories", "language": "Khasi", "is_translation": False},
    {"id": 21, "title": "9 Tylli Ki Biria Dei Por", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Short stories", "language": "Khasi", "is_translation": False},
    {"id": 22, "title": "Ki Phawer U A. Sun – Volume I", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Short stories", "language": "Khasi", "is_translation": False},
    {"id": 23, "title": "Ki Phawer U A. Sun – Volume II", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Short stories", "language": "Khasi", "is_translation": False},
    {"id": 24, "title": "Ki Phawer U A. Sun – Volume III", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Short stories", "language": "Khasi", "is_translation": False},
    {"id": 25, "title": "Ka Thapbalieh Bad Kiwei De Ki Khana", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Stories", "language": "Khasi", "is_translation": False},
    {"id": 26, "title": "Ki Biria U Thmoin", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},
    {"id": 27, "title": "Ka Sympa", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},
    {"id": 28, "title": "Ka Premmiet Khatduh", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},
    {"id": 29, "title": "La Phon Ka Kper Tyrso", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},
    {"id": 30, "title": "Ka Melody", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Fiction", "language": "Khasi", "is_translation": False},

    # B. Khasi poetry
    {"id": 31, "title": "Ka Duitara Ksiar", "author": "Soso Tham", "genre": "Original Khasi literature", "type": "Poetry", "year": 1925, "language": "Khasi", "is_translation": False},
    {"id": 32, "title": "Ki Sngi Barim U Hynñiew Trep", "author": "Soso Tham", "genre": "Original Khasi literature", "type": "Poetry", "year": 1936, "language": "Khasi", "is_translation": False},
    {"id": 33, "title": "Na Lum Khasi", "author": "D.S. Khongdup", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 34, "title": "Ka Ryngkap", "author": "Morkha Joseph", "genre": "Original Khasi literature", "type": "Poetry", "year": 1897, "language": "Khasi", "is_translation": False},
    {"id": 35, "title": "Ka Jutang Sur Pangnud U Khun Khasi", "author": "O.M. Wahlang", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 36, "title": "Ka Kitap Jingphawar", "author": "Rabon Singh", "genre": "Original Khasi literature", "type": "Poetry / Folklore", "language": "Khasi", "is_translation": False},
    {"id": 37, "title": "Ki Poetry Khasi", "author": "V.G. Bareh", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 38, "title": "Ka Hamsaia Ki Por", "author": "H. Elias", "genre": "Original Khasi literature", "type": "Poetry / Criticism", "language": "Khasi", "is_translation": False},
    {"id": 39, "title": "Ka Burom Ba La Jah II", "author": "H.W. Sten", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 40, "title": "Ka Umpohliew", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 41, "title": "Ki Sur Ba Dang Sawa", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 42, "title": "Ki Sur Shongsbai", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 43, "title": "Hima Jingieit Jong Nga", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 44, "title": "Ki Sur Bat Kpoh", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Humorous poetry", "language": "Khasi", "is_translation": False},
    {"id": 45, "title": "Kiba Nga Ñiewkor", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 46, "title": "Ki Matti I Khasi", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 47, "title": "Ki Mawkordor Ka Iing Ka Sem", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 48, "title": "9 Tylli Ki Mawkordor", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 49, "title": "Ka Shatai – Ka Tiew Larun", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 50, "title": "Meghalaya – Ka Ri Baieit", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 51, "title": "Ka Ri Jong Ngi", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 52, "title": "Kiba Nga Ieit & Ñiewburom", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 53, "title": "Ki Sur Pangnud Na Krem Shadem", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 54, "title": "Ki Khyrdong U ’Sai Muka", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 55, "title": "Shi Kynthup Ki Mieng Sahsnem", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Sonnets", "language": "Khasi", "is_translation": False},
    {"id": 56, "title": "Ki Um Khlur Ba Dang Jreiñ", "author": "Andreas Sun", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 57, "title": "Na Khriang Ka Dohnud", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 58, "title": "Ki Umjer Rupa", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 59, "title": "Na Lyngwiar Dpei I Mei", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Folk poetry", "language": "Khasi", "is_translation": False},
    {"id": 60, "title": "Na Thwei Pyrkhat U Longshuwa", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Folk poetry", "language": "Khasi", "is_translation": False},
    {"id": 61, "title": "Na Ki Sawkun Ka Mariang", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Environmental poetry", "language": "Khasi", "is_translation": False},
    {"id": 62, "title": "Ki Kyrpien Jong Ka Por Ki Tanka Ha Ka Khasi Bad Kiwei De Ki Poim", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Poetry / Tanka", "language": "Khasi", "is_translation": False},
    {"id": 63, "title": "Ki Mawjam Ka Jingim", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 64, "title": "Na Tyllong Ki Umpohliew", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 65, "title": "Ki Jingsngew Ka Dohnud", "author": "Lucky Kharpuri", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 66, "title": "Ki Syrwet Ba La Lumlang", "author": "Lucky Kharpuri", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 67, "title": "Na Ki Kyntem Ba La Lumlang", "author": "Lucky Kharpuri", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 68, "title": "Ki Sur Kyllum", "author": "Minimon Laloo", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 69, "title": "Ki Sur Bathiang", "author": "Minimon Laloo", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 70, "title": "Ki Poitri Khasi", "author": "Hamlet Pariat", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 71, "title": "Syntiew Parom", "author": "Sumar Sing Sawian", "genre": "Original Khasi literature", "type": "Poetry / Folk", "language": "Khasi", "is_translation": False},
    {"id": 72, "title": "Ki Syrwet Ka Dohnud", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 73, "title": "Ki Sur Ka Synnia", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Poetry", "language": "Khasi", "is_translation": False},
    {"id": 74, "title": "Ka Jingai Sngewbha", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 75, "title": "La Pulom Ei", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 76, "title": "Balei Kumne?", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 77, "title": "Ieit Ia Ka Jot", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 78, "title": "Ioh Phi Babe", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 79, "title": "Tang Ma Phi", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 80, "title": "Shi Khra Ka Tyngka", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 81, "title": "Ap Ia Nga", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 82, "title": "Ka Khmat Miet", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 83, "title": "Phi Da Ieit Shisha Ne Em?", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},
    {"id": 84, "title": "La Syntuid Ka Hok", "author": "Phrikshon Kharshiing", "genre": "Original Khasi literature", "type": "Literary work", "language": "Khasi", "is_translation": False},

    # C. Khasi drama and plays
    {"id": 85, "title": "U Baieit Donshkor", "author": "D.S. Khongdup", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 86, "title": "Ka Rangli", "author": "H. Mylliemngap", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 87, "title": "Ka Mahadei", "author": "H.W. Sten", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 88, "title": "U Raikut", "author": "S. Dkhar", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 89, "title": "Ka Sawangka U Raikut", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 90, "title": "U Androklis Bad U Sing", "author": "S.J. Duncan", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 91, "title": "U Banlum Bad Ka Baïa", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 92, "title": "Ka Latympang", "author": "Streamlet Dkhar", "genre": "Original Khasi literature", "type": "Poetic drama", "language": "Khasi", "is_translation": False},
    {"id": 93, "title": "Ka Puri Dieng", "author": "K.K. Kharlukhi", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 94, "title": "Ka Shatsngi", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 95, "title": "Ka Rimon", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 96, "title": "Ka Tiewbon", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 97, "title": "U SBE", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 98, "title": "Ngam Lah Ban Klet", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Dialogue / Drama", "language": "Khasi", "is_translation": False},
    {"id": 99, "title": "Ka Shangkhawiah Ki Rang", "author": "Anonymous", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 100, "title": "Ka Sawangka Ia Ki Sawngut Ba Iap Mynsaw", "author": "F.M. Pugh", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 101, "title": "Haba Ka Kupar Jot Ka Dawa", "author": "Anthony Jala", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 102, "title": "Ka Kyiad", "author": "L.H. Pde", "genre": "Original Khasi literature", "type": "Drama", "language": "Khasi", "is_translation": False},
    {"id": 103, "title": "Ka Jinglong Tynrai U Briew Katkum Ki Drama Khasi", "author": "Streamlet Dkhar", "genre": "Khasi nonfiction / criticism", "type": "Drama criticism", "language": "Khasi", "is_translation": False},
    {"id": 104, "title": "Ka Jingbishar Ia Ka Shangkhawiah Ki Rang", "author": "Streamlet Dkhar", "genre": "Khasi nonfiction / criticism", "type": "Drama criticism", "language": "Khasi", "is_translation": False},
    {"id": 105, "title": "Ka Jingbishar Ia Ka Drama U Baieit Donshkor", "author": "Streamlet Dkhar", "genre": "Khasi nonfiction / criticism", "type": "Drama criticism", "language": "Khasi", "is_translation": False},

    # D. Khasi history and historical books
    {"id": 106, "title": "History of India in Khasi", "author": "Jeebon Roy", "genre": "Khasi history/culture", "type": "History", "year": 1900, "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 107, "title": "Ka History Jong Ka Ri Khasi", "author": "B.K. Sarma Roy", "genre": "Khasi history/culture", "type": "History", "year": 1908, "language": "Khasi", "is_translation": False},
    {"id": 108, "title": "Shaphang Ki Syiem Nongkhlaw", "author": "B.K. Sarma Roy", "genre": "Khasi history/culture", "type": "History", "year": 1908, "language": "Khasi", "is_translation": False},
    {"id": 109, "title": "Ka Histori Ka Ri Assam", "author": "Theodore Cajee", "genre": "Khasi history/culture", "type": "History", "year": 1936, "language": "Khasi", "is_translation": False},
    {"id": 110, "title": "Ki Syiem Khasi Bad Synteng", "author": "H. Lyngdoh", "genre": "Khasi history/culture", "type": "History", "year": 1938, "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 111, "title": "Ka History Ka Thma Pyrthei Ba-ar I", "author": "L.L.D. Basan", "genre": "Khasi history/culture", "type": "History", "year": 1941, "language": "Khasi", "is_translation": False},
    {"id": 112, "title": "Ka History Ka Thma Pyrthei Ba-ar II", "author": "L.L.D. Basan", "genre": "Khasi history/culture", "type": "History", "year": 1944, "language": "Khasi", "is_translation": False},
    {"id": 113, "title": "Ka History Ka Thoh Ka Tar – Bynta I", "author": "R.S. Lyngdoh", "genre": "Khasi history/culture", "type": "Literary history", "year": 1983, "language": "Khasi", "is_translation": False},
    {"id": 114, "title": "Ka History Ka Thoh Ka Tar – Bynta II", "author": "R.S. Lyngdoh", "genre": "Khasi history/culture", "type": "Literary history", "year": 1979, "language": "Khasi", "is_translation": False},
    {"id": 115, "title": "Ka Thymmei Jingtip Shaphang Ka Thoh Ka Tar", "author": "M.G. Lyngdoh", "genre": "Khasi history/culture", "type": "History", "year": 1981, "language": "Khasi", "is_translation": False},
    {"id": 116, "title": "Ka Jingïathuhkhana Pateng Shaphang Ki Syiem Jong Ka Hima Mylliem", "author": "Jor Manik Syiem", "genre": "Khasi history/culture", "type": "Oral history", "year": 1984, "language": "Khasi", "is_translation": False},
    {"id": 117, "title": "Ka History Ka Ri Khasi-Jaiñtia", "author": "Kong Tngensi", "genre": "Khasi history/culture", "type": "History", "year": 1988, "language": "Khasi", "is_translation": False},
    {"id": 118, "title": "Ka History Ka Ri Khasi-Jaiñtia Part II Vol. II", "author": "Kong Tngensi", "genre": "Khasi history/culture", "type": "History", "year": 1991, "language": "Khasi", "is_translation": False},
    {"id": 119, "title": "Ka History Ka Ri Khasi-Jaiñtia Part II Vol. III", "author": "Kong Tngensi", "genre": "Khasi history/culture", "type": "History", "language": "Khasi", "is_translation": False},
    {"id": 120, "title": "Ka Shillong Naduh Ka Snem 1863 Part I & II", "author": "L. Gilbert Shullai", "genre": "Khasi history/culture", "type": "Urban history", "year": 1998, "language": "Khasi", "is_translation": False},
    {"id": 121, "title": "Ka History Ka Raid Nongbri", "author": "Hiarless Tmung", "genre": "Khasi history/culture", "type": "Local history", "year": 2006, "language": "Khasi", "is_translation": False},
    {"id": 122, "title": "U Thomas Jones Bad Ka Pyrthei Saitsohpen", "author": "S.S. Majaw", "genre": "Khasi history/culture", "type": "Biographical history", "year": 2011, "language": "Khasi", "is_translation": False},
    {"id": 123, "title": "Ki Sngi Jong U Thomas Jones II", "author": "S.S. Majaw", "genre": "Khasi history/culture", "type": "Biographical history", "year": 2014, "language": "Khasi", "is_translation": False},
    {"id": 124, "title": "Ka History Jong Ka Khasi-Jaiñtia Bad Assam", "author": "F.M. Pugh", "genre": "Khasi history/culture", "type": "Regional history", "language": "Khasi", "is_translation": False},
    {"id": 125, "title": "Ka History Jong Ka Ri India", "author": "F.M. Pugh", "genre": "Khasi history/culture", "type": "National history", "language": "Khasi", "is_translation": False},
    {"id": 126, "title": "U Khasi Ha Ka Por U Phareng", "author": "Helen Syiem", "genre": "Khasi history/culture", "type": "Colonial history", "language": "Khasi", "is_translation": False},
    {"id": 127, "title": "Ka History Jong Ka Hima Mawlong", "author": "E.W. Chyne", "genre": "Khasi history/culture", "type": "State history", "language": "Khasi", "is_translation": False},
    {"id": 128, "title": "Shispah Sanphew Snem Mynshwa, U Tirot Singh Bad Ka Mynnor Ba I Puhiphen", "author": "Khasi Cultural Society", "genre": "Khasi history/culture", "type": "Historical monograph", "language": "Khasi", "is_translation": False},

    # E. Khasi culture, religion and society
    {"id": 129, "title": "Ka Niam Jong Ki Khasi", "author": "Jeebon Roy", "genre": "Khasi religious literature", "type": "Khasi religion / Culture", "year": 1897, "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 130, "title": "Ka Riti Jong Ka Ri Laiphew Syiem", "author": "G. Costa", "genre": "Khasi history/culture", "type": "Khasi customary law", "year": 1937, "language": "Khasi", "is_translation": False},
    {"id": 131, "title": "Ka Pyrkhat U Khasi", "author": "H.O. Mawrie", "genre": "Khasi history/culture", "type": "Culture / Philosophy", "year": 1973, "language": "Khasi", "is_translation": False},
    {"id": 132, "title": "Ka Ksaw Ka Kpong U Hynñiew Trep", "author": "D.T. Laloo", "genre": "Khasi history/culture", "type": "Folklore / Customs", "language": "Khasi", "is_translation": False},
    {"id": 133, "title": "Ka Niam Khasi", "author": "H. Lyngdoh", "genre": "Khasi religious literature", "type": "Religion / Customs", "year": 1937, "language": "Khasi", "is_translation": False},
    {"id": 134, "title": "Ka Niam Ki Khasi – Ka Niam Tip Blei Tip Briew", "author": "Sib Charan Roy", "genre": "Khasi religious literature", "type": "Theology / Ethics", "year": 1919, "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 135, "title": "Ka Jingim U Trai Jong Ngi", "author": "Anonymous", "genre": "Khasi religious literature", "type": "Religious biography", "language": "Khasi", "is_translation": True, "digitized": True},
    {"id": 136, "title": "Ka Jingbam Ka Mynsiem", "author": "Anonymous", "genre": "Khasi religious literature", "type": "Spiritual devotional", "language": "Khasi", "is_translation": True, "digitized": True},
    {"id": 137, "title": "Ka Jingbatai Lyngkot Ia Ki Kambah", "author": "Anonymous", "genre": "Khasi religious literature", "type": "Theological tract", "language": "Khasi", "is_translation": True, "digitized": True},
    {"id": 138, "title": "Ha Ki Kjat U Kynrad", "author": "Anonymous", "genre": "Khasi religious literature", "type": "Devotional hymns", "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 139, "title": "Ka Kitab Ba Batai Pynshynna Shaphang Uwei U Blei", "author": "Anonymous", "genre": "Khasi religious literature", "type": "Monotheism treatise", "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 140, "title": "Ka Kitab Khasi Kaba Ar", "author": "Jeebon Roy", "genre": "Khasi school textbooks", "type": "Reader / Educational", "year": 1899, "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 141, "title": "Ka Kitab Khasi Kaba Lai", "author": "Jeebon Roy", "genre": "Khasi school textbooks", "type": "Reader / Educational", "year": 1900, "language": "Khasi", "is_translation": False, "digitized": True},
    {"id": 142, "title": "Ka Jingai Bakordor I", "author": "K.W. Nongrum", "genre": "Khasi religious literature", "type": "Moral discourse", "language": "Khasi", "is_translation": False},
    {"id": 143, "title": "Ka Jingai Bakordor II", "author": "K.W. Nongrum", "genre": "Khasi religious literature", "type": "Moral discourse", "language": "Khasi", "is_translation": False},
    {"id": 144, "title": "Kiba Nga Ñiew Burom", "author": "K.W. Nongrum", "genre": "Original Khasi literature", "type": "Literary reflections", "language": "Khasi", "is_translation": False},

    # F. Khasi language, grammar and linguistic books
    {"id": 145, "title": "Ka English Grammar (Ha Ka Khasi)", "author": "Chandra Nath Roy", "genre": "Khasi grammar/linguistics", "type": "Grammar", "year": 1909, "language": "Khasi / English", "is_translation": False},
    {"id": 146, "title": "Essay Hints To Easy Grammar", "author": "B.K. Sarma Roy", "genre": "Khasi grammar/linguistics", "type": "Pedagogical grammar", "year": 1900, "language": "Khasi / English", "is_translation": False},
    {"id": 147, "title": "Hints On Study Of Khasi Language", "author": "Nissor Singh L. Nongbri", "genre": "Khasi grammar/linguistics", "type": "Linguistic guide", "year": 1900, "language": "Khasi / English", "is_translation": False},
    {"id": 148, "title": "Khasi English Course And Grammar", "author": "Mondon Bareh", "genre": "Khasi grammar/linguistics", "type": "Comprehensive grammar", "year": 1929, "language": "Khasi / English", "is_translation": False, "digitized": True},
    {"id": 149, "title": "Ka Anglo Khasi Primer", "author": "Mondon Bareh", "genre": "Khasi grammar/linguistics", "type": "Primer", "year": 1930, "language": "Khasi / English", "is_translation": False},
    {"id": 150, "title": "New English Primer With Khasi", "author": "D.N.S. Wahlang", "genre": "Khasi grammar/linguistics", "type": "Primer", "year": 1931, "language": "Khasi / English", "is_translation": False},
    {"id": 151, "title": "Model English Translation", "author": "D.N.S. Wahlang", "genre": "Khasi grammar/linguistics", "type": "Translation guide", "year": 1931, "language": "Khasi / English", "is_translation": False},
    {"id": 152, "title": "Ka Khasi Phareng Hindustani And Grammar", "author": "Joab Solomon", "genre": "Khasi grammar/linguistics", "type": "Multilingual grammar", "year": 1932, "language": "Khasi / English / Hindustani", "is_translation": False},
    {"id": 153, "title": "Ka Grammar Khasi", "author": "H. Elias", "genre": "Khasi grammar/linguistics", "type": "Descriptive grammar", "year": 1956, "language": "Khasi", "is_translation": False},
    {"id": 154, "title": "Ka Daialok", "author": "F.M. Pugh", "genre": "Khasi grammar/linguistics", "type": "Dialectology", "year": 1960, "language": "Khasi", "is_translation": False},
    {"id": 155, "title": "Ka Grammar Phareng (Ha Ka Ktien Khasi)", "author": "E. Blah", "genre": "Khasi grammar/linguistics", "type": "Grammar", "year": 1963, "language": "Khasi / English", "is_translation": False},
    {"id": 156, "title": "Ka Jingïar Ka Ktien Khasi Bynta I & II", "author": "F.M. Pugh", "genre": "Khasi grammar/linguistics", "type": "Linguistic expansion", "year": 1966, "language": "Khasi", "is_translation": False},
    {"id": 157, "title": "Grammar And Composition For The Khasi M.E. School", "author": "Justman Kharmih", "genre": "Khasi grammar/linguistics", "type": "School grammar", "year": 1971, "language": "Khasi / English", "is_translation": False},
    {"id": 158, "title": "Ka Grammar Khasi", "author": "F.D. Basaïawmoit", "genre": "Khasi grammar/linguistics", "type": "Grammar", "year": 1974, "language": "Khasi", "is_translation": False},
    {"id": 159, "title": "Ka Grammar", "author": "H.W. Sten", "genre": "Khasi grammar/linguistics", "type": "Grammar", "year": 1987, "language": "Khasi", "is_translation": False},
    {"id": 160, "title": "Ki Verb Khasi", "author": "H. Marweiñ", "genre": "Khasi grammar/linguistics", "type": "Morphology / Verbs", "year": 1990, "language": "Khasi", "is_translation": False},
    {"id": 161, "title": "Shaphang Ka Ktien Khasi", "author": "H.W. Sten", "genre": "Khasi grammar/linguistics", "type": "General linguistics", "year": 1991, "language": "Khasi", "is_translation": False},
    {"id": 162, "title": "Ka Jingpule Shaphang Ka Ktien", "author": "M.B. Jyrwa", "genre": "Khasi grammar/linguistics", "type": "Linguistics", "year": 1995, "language": "Khasi", "is_translation": False},
    {"id": 163, "title": "U Khasi Bad Ka Buhrieh Ktien", "author": "S.F. Rynjah", "genre": "Khasi grammar/linguistics", "type": "Semantics / Idiom", "year": 1997, "language": "Khasi", "is_translation": False},
    {"id": 164, "title": "Khasi Through English", "author": "H.W. Sten", "genre": "Khasi grammar/linguistics", "type": "Pedagogical course", "year": 1997, "language": "Khasi / English", "is_translation": False},
    {"id": 165, "title": "Khasi Komposishon", "author": "E.W. Dkhar", "genre": "Khasi grammar/linguistics", "type": "Composition", "year": 1999, "language": "Khasi", "is_translation": False},
    {"id": 166, "title": "Ka Shim Kylliang Kyntien Ha Ka Khasi", "author": "Bakhiamon Rynjah", "genre": "Khasi grammar/linguistics", "type": "Lexical borrowing", "year": 2000, "language": "Khasi", "is_translation": False},
    {"id": 167, "title": "Ki Sawa Bad Ki Dur Kyntien Jong Ka Ktien Khasi", "author": "B. War", "genre": "Khasi grammar/linguistics", "type": "Phonology & Morphology", "year": 2001, "language": "Khasi", "is_translation": False},
    {"id": 168, "title": "Ka Jinghikai Ia Ka Ktien Khasi", "author": "A. Kharmalki", "genre": "Khasi grammar/linguistics", "type": "Language pedagogy", "year": 2002, "language": "Khasi", "is_translation": False},
    {"id": 169, "title": "English Grammar In Khasi", "author": "M. Diengdoh", "genre": "Khasi grammar/linguistics", "type": "Grammar", "year": 2003, "language": "Khasi / English", "is_translation": False},
    {"id": 170, "title": "Ki Nongrim Ka Pule Ktien Bad Hikai Ktien", "author": "A. Kharmalki", "genre": "Khasi grammar/linguistics", "type": "Linguistic foundations", "year": 2006, "language": "Khasi", "is_translation": False},
    {"id": 171, "title": "Ka Grammar Lyngkot Na Ka Bynta Ki Khynnah Skul Lower Primary", "author": "K. Rapthap", "genre": "Khasi grammar/linguistics", "type": "Elementary grammar", "year": 2009, "language": "Khasi", "is_translation": False},
    {"id": 172, "title": "Khasi Proverb", "author": "Solony Bareh", "genre": "Khasi oral literature / folklore", "type": "Paremiology", "year": 2011, "language": "Khasi / English", "is_translation": False},
    {"id": 173, "title": "Ka Kot Ïarap English Grammar", "author": "F. Kharjana", "genre": "Khasi grammar/linguistics", "type": "Grammar guide", "year": 2014, "language": "Khasi / English", "is_translation": False},
    {"id": 174, "title": "Ka Thup Ki Lai Sker", "author": "L.H. Pde", "genre": "Khasi grammar/linguistics", "type": "Morphology", "year": 2014, "language": "Khasi", "is_translation": False},
    {"id": 175, "title": "Ki Jait Ktien Bad Ki Ktien Tnat Jong Ka Meghalaya", "author": "B. War et al.", "genre": "Khasi grammar/linguistics", "type": "Dialectology", "year": 2014, "language": "Khasi", "is_translation": False},
    {"id": 176, "title": "Ka Matiang Ka Grammar Khasi", "author": "Loloshon Marbañiang", "genre": "Khasi grammar/linguistics", "type": "Structural grammar", "year": 2015, "language": "Khasi", "is_translation": False},
    {"id": 177, "title": "Process Of Standardization Of Khasi Language", "author": "Ailynti Nongbri", "genre": "Khasi grammar/linguistics", "type": "Sociolinguistics", "year": 2012, "language": "English / Khasi", "is_translation": False},
    {"id": 178, "title": "Ka Krammar Khasi Kitab I", "author": "KJWA Research Cell", "genre": "Khasi grammar/linguistics", "type": "Standard grammar", "year": 2017, "language": "Khasi", "is_translation": False},
    {"id": 179, "title": "Ka Krammar Khasi Kitab II", "author": "KJWA Research Cell", "genre": "Khasi grammar/linguistics", "type": "Standard grammar", "year": 2017, "language": "Khasi", "is_translation": False},
    {"id": 180, "title": "Ka Krammar Khasi Kitab III", "author": "KJWA Research Cell", "genre": "Khasi grammar/linguistics", "type": "Standard grammar", "year": 2017, "language": "Khasi", "is_translation": False},
    {"id": 181, "title": "Ka Krammar Khasi Kitab IV", "author": "KJWA Research Cell", "genre": "Khasi grammar/linguistics", "type": "Standard grammar", "year": 2018, "language": "Khasi", "is_translation": False},

    # G. Khasi dictionaries and reference works
    {"id": 182, "title": "Anglo-Khasi Dictionary", "author": "Hugh Roberts", "genre": "Khasi dictionaries", "type": "Bilingual dictionary", "year": 1870, "language": "English - Khasi", "is_translation": False},
    {"id": 183, "title": "The Khasi Dictionary", "author": "Job Solomon", "genre": "Khasi dictionaries", "type": "General dictionary", "year": 1895, "language": "Khasi", "is_translation": False},
    {"id": 184, "title": "Khasi-English Dictionary", "author": "Nissor Singh", "genre": "Khasi dictionaries", "type": "Bilingual dictionary", "year": 1904, "language": "Khasi - English", "is_translation": False, "digitized": True},
    {"id": 185, "title": "English-Khasi Dictionary", "author": "Nissor Singh", "genre": "Khasi dictionaries", "type": "Bilingual dictionary", "year": 1920, "language": "English - Khasi", "is_translation": False, "digitized": True},
    {"id": 186, "title": "English-Khasi Dictionary", "author": "Amirkha Chyne", "genre": "Khasi dictionaries", "type": "Bilingual dictionary", "year": 1922, "language": "English - Khasi", "is_translation": False},
    {"id": 187, "title": "Ka Jingspel Bad Ka Dikshoneri Khasi", "author": "T. Cajee", "genre": "Khasi dictionaries", "type": "Orthography & Dictionary", "year": 1937, "language": "Khasi", "is_translation": False},
    {"id": 188, "title": "Anglo-Khasi Dictionary", "author": "A.K. Diengdoh", "genre": "Khasi dictionaries", "type": "Bilingual dictionary", "year": 1966, "language": "English - Khasi", "is_translation": False},
    {"id": 189, "title": "Leemuel’s Pocket Anglo-Khasi Dictionary", "author": "A.K. Diengdoh", "genre": "Khasi dictionaries", "type": "Pocket dictionary", "year": 1966, "language": "English - Khasi", "is_translation": False},
    {"id": 190, "title": "Khasi-English Dictionary", "author": "A.K. Diengdoh", "genre": "Khasi dictionaries", "type": "Bilingual dictionary", "year": 1967, "language": "Khasi - English", "is_translation": False},
    {"id": 191, "title": "Ka Dinshonhi (Khasi-Khasi Dictionary)", "author": "Iarington Kharkongor", "genre": "Khasi dictionaries", "type": "Monolingual dictionary", "year": 1968, "language": "Khasi", "is_translation": False},
    {"id": 192, "title": "Khasi-English Dictionary", "author": "E. Bars", "genre": "Khasi dictionaries", "type": "Major bilingual dictionary", "year": 1973, "language": "Khasi - English", "is_translation": False},
    {"id": 193, "title": "A Khasi Glossary", "author": "Iarington Kharkongor", "genre": "Khasi dictionaries", "type": "Glossary", "year": 1973, "language": "Khasi", "is_translation": False},
    {"id": 194, "title": "Aramaik-Khasi & Hebru-Khasi Dictionary", "author": "Rev. Fr. S. Sngi Lyngdoh", "genre": "Khasi dictionaries", "type": "Biblical dictionary", "year": 1975, "language": "Aramaic / Hebrew - Khasi", "is_translation": False},
    {"id": 195, "title": "Greek-Khasi Dictionary", "author": "Rev. Fr. S. Sngi Lyngdoh", "genre": "Khasi dictionaries", "type": "Biblical dictionary", "year": 1975, "language": "Greek - Khasi", "is_translation": False},
    {"id": 196, "title": "English-Khasi Dictionary", "author": "E. Blah & L. Harrison", "genre": "Khasi dictionaries", "type": "Bilingual dictionary", "year": 1976, "language": "English - Khasi", "is_translation": False},
    {"id": 197, "title": "Ka Dikshoneri I – Ki Kyrteng Ha Ka Baibl", "author": "P.T. Marwein", "genre": "Khasi dictionaries", "type": "Biblical names dictionary", "year": 2000, "language": "Khasi", "is_translation": False},
    {"id": 198, "title": "Ka Dikshoneri II – Ki Ktien Ha Ka Baibl", "author": "P.T. Marwein", "genre": "Khasi dictionaries", "type": "Biblical terms dictionary", "year": 2003, "language": "Khasi", "is_translation": False},
    {"id": 199, "title": "Ka Dikshoneri III – Jinglamphrang Ka Testament Barim", "author": "P.T. Marwein", "genre": "Khasi dictionaries", "type": "Old Testament dictionary", "year": 2006, "language": "Khasi", "is_translation": False},
    {"id": 200, "title": "Ka Dikshoneri IV – Jinglamphrang Ka Testament Bathymmai", "author": "P.T. Marwein", "genre": "Khasi dictionaries", "type": "New Testament dictionary", "year": 2010, "language": "Khasi", "is_translation": False},
    {"id": 201, "title": "Ka Modern English-Khasi Dictionary", "author": "Fr. Francis Kharwanlang", "genre": "Khasi dictionaries", "type": "Modern dictionary", "year": 2010, "language": "English - Khasi", "is_translation": False},
    {"id": 202, "title": "A Dictionary Of Khasi Literature", "author": "O.L. Snaitang", "genre": "Khasi dictionaries", "type": "Literary dictionary", "year": 2011, "language": "English / Khasi", "is_translation": False},
    {"id": 203, "title": "Ka Modern English-Khasi Dictionary (Ka Thiar Kyntien)", "author": "Fr. Francis Kharwanlang", "genre": "Khasi dictionaries", "type": "Lexicon (Ka Thiar Kyntien)", "year": 2015, "language": "English - Khasi", "is_translation": False},
    {"id": 204, "title": "Ka Batai Kyntien", "author": "Antoinette Kharmalki", "genre": "Khasi dictionaries", "type": "Vocabulary & definitions", "year": 2015, "language": "Khasi", "is_translation": False}
]

def compile():
    with open(CATALOGUE_PATH, "w", encoding="utf-8") as f:
        json.dump(RAW_CATALOGUE, f, indent=2, ensure_ascii=False)
    print(f"Successfully compiled {len(RAW_CATALOGUE)} works into {CATALOGUE_PATH}")

if __name__ == "__main__":
    compile()
